### ISSUE TITLE
rules.json: allow the SearXNG embedded image proxy

### ISSUE THREAD

**Issue by dalf** [searxng/filtron#1]
Backport of https://github.com/paulgoio/searxng/blob/main/src/rules.json

Sandbox:
* https://sandbox.al-f.net
* https://sandbox.al-f.net/rules

It seems to work.

ping @mrpaulblack

**Comment by mrpaulblack** [comment]
nope; still broken... My workaround atm is to add a stop to the subrule def. in /image_proxy.:
https://github.com/paulgoio/searxng/blob/187a70589eeb3b613ff17330fa9e1ce213fab4e6/src/rules.json#L11

Meaning that there is no rate limiting and blocking going on for the /image_proxy path. If I remove the stop rule there requests get rate limited after a burst of around 30 requests... (you can test this with image category...)

Maybe this line does not get triggered properly, but idk:
https://github.com/paulgoio/searxng/blob/187a70589eeb3b613ff17330fa9e1ce213fab4e6/src/rules.json#L82

**Comment by return42** [comment]
Can we close this issue?

**Comment by mrpaulblack** [comment]
> I think we can close this when we merge https://github.com/searxng/searxng/pull/618 ; Right now there is a workaround in the rules.json in my fork to make the image_proxy work and image_proxy is going to have rate limiting issues upstream...

**Comment by mrpaulblack** [comment]
We are not using filtron anymore and are switching to the limiter plugin; Closing.
