### ISSUE TITLE
rules.json: Make it part of the image

### ISSUE THREAD

**Issue by mrpaulblack** [searxng/filtron#4]
Right now searxng-docker uses dalf/filtron:latest as the image for filtron. Since we have filtron in the repo now we should setup github actions to bould images and push them to the searxng org.

Furthermore I think we should include the default rules.json from searxng-docker since in most cases people are just mounting that file inside their filtron container anyway. This way the file stays up to date, the container does not require mounting (and before that creating) a file and easier config for new maintainers. If anyway wants to change the rules.json they can just mount a custom one into the container at the location of the default one.

**Comment by return42** [comment]
> Right now searxng-docker uses dalf/filtron:latest as the image for filtron. Since we have filtron in the repo now we should setup github actions to bould images and push them to the searxng org.

related to: https://github.com/searxng/searxng-docker/pull/5
